name: Update Language Stats

on:
    schedule:
        - cron: "0 0 * * 1" # Every Monday
    workflow_dispatch:

jobs:
    update-stats:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout (with submodules)
              uses: actions/checkout@v3
              with:
                  submodules: recursive

            - name: Run self-reposcope
              uses: 4okimi7uki/self-reposcope-action@v1.0.1
              with:
                  github_token: ${{ secrets.REPOSCOPE_TOKEN }}

            - name: Copy output 
              shell: bash
              run: |
                  cp -r ./tools/self-reposcope/output .
