name: Update Language Stats

on:
    schedule:
        - cron: "0 0 * * 1" # Every Monday
    workflow_dispatch:

jobs:
    update-stats:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Run self-reposcope
              uses: 4okimi7uki/self-reposcope-action@v1
              with:
                  github_token: ${{ secrets.REPOSCOPE_TOKEN }}
